### ISSUE TITLE
A post from AAAAA was not parsable

### ISSUE THREAD

**Issue by wacher74** [TumblThreeApp/TumblThree#157]
When I start a scanning I get this message:
"A post from AAAAA was not parsable. Setting 'posts per page' to 1 in the Details might increase the downlaodable content.
If i hover previous message with mouse then I get
"Internal error description
Expecting element 'root' from namepsace ''.. Encountered 'None' with name '', namepsace ''.

**Log details:**
20210610 11:08:04.924	Inf 	IsLongPathSupported: True
20210610 11:08:19.103	Vrb 	TumblrLikedByCrawler.Crawl:Start
20210610 11:08:20.438	Err 	AbstractCrawler:ConvertJsonToClass<T>: Could not parse data
20210610 11:08:20.454	Vrb 	TumblrLikedByCrawler:CrawlPageAsync: System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at TumblThree.Applications.Crawler.AbstractTumblrCrawler.RetrieveOriginalImageUrl(String url, Int32 width, Int32 height) in C:\projects\Tumblthree\src\TumblThree\TumblThree.Applications\Crawler\AbstractTumblrCrawler.cs:line 360
   at TumblThree.Applications.Crawler.AbstractTumblrCrawler.AddTumblrPhotoUrl(String text, Post post) in C:\projects\Tumblthree\src\TumblThree\TumblThree.Applications\Crawler\AbstractTumblrCrawler.cs:line 237
   at TumblThree.Applications.Crawler.TumblrLikedByCrawler.AddPhotoUrlToDownloadList(String document) in C:\projects\Tumblthree\src\TumblThree\TumblThree.Applications\Crawler\TumblrLikedByCrawler.cs:line 285
   at TumblThree.Applications.Crawler.TumblrLikedByCrawler.<AddUrlsToDownloadListAsync>d__12.MoveNext() in C:\projects\Tumblthree\src\TumblThree\TumblThree.Applications\Crawler\TumblrLikedByCrawler.cs:line 226
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TumblThree.Applications.Crawler.TumblrLikedByCrawler.<CrawlPageAsync>d__7.MoveNext() in C:\projects\Tumblthree\src\TumblThree\TumblThree.Applications\Crawler\TumblrLikedByCrawler.cs:line 109

**Desktop (please complete the following information):**
 - TumblThree version: 1.4 - 1.6
 - OS: Windows 10 Pro

What can I do?
By the way, there is not such 'post per page' in Details.

**Comment by thomas694** [comment]
Hello,
thanks for reporting the bug.
We already found the problem, Tumblr changed one of it's message formats. The newest version can download these posts again.

**Comment by thomas694** [comment]
The issue has been fixed and closed. You can still comment. Feel free to ask for reopening the issue if needed.

**Comment by wacher74** [comment]
It's not working.
"A post from AAAAA was not parsable. Setting 'posts per page' to 1 in the Details might increase the downlaodable content.
If i hover previous message with mouse then I get

Accessed JArray values with invalid key value: "0". Int32 array index expected.

**Comment by thomas694** [comment]
Yes, unfortunately they use different (at least two) formats depending on the condition/blog. We have to look again.

**Comment by thomas694** [comment]
Please check the new version.

**Comment by thomas694** [comment]
General note:
Depending on the blogs you have and whether you are using the image size "best", it might be good to crawl your blogs which contain larger images once with the option "force rescan" as previously not all posts have been downloaded properly.

**Comment by wacher74** [comment]
Thank you very much, it is working again.
