### ISSUE TITLE
Queue won't run

### ISSUE THREAD

**Issue by MSWallack** [TumblThreeApp/TumblThree#159]
Since upgrading to v1.6.2, my queue won't run at all. I can add blogs to the queue, but when I press the Crawl button nothing happens. Further, if I stop the crawl I am then unable to try to start the crawl again until I've closed and restarted the app.

**Comment by thomas694** [comment]
Hello,
can you find any hints/errors in your TumblThree log file?

**Comment by MSWallack** [comment]
Where do I find the log file?

**Comment by thomas694** [comment]
normally %LOCALAPPDATA%\TumblThree

**Comment by MSWallack** [comment]
Not sure if this helps... (checked after restarting the computer and starting a new log file):

20210617 22:08:29.581	Inf 	IsLongPathSupported: True
20210617 22:20:00.390	Err 	Unobserved task exception: System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at TumblThree.Domain.Models.Files.Files.LoadCore(String fileLocation) in C:\projects\Tumblthree\src\TumblThree\TumblThree.Domain\Models\Files\Files.cs:line 159
   at TumblThree.Domain.Models.Files.Files.Load(String fileLocation) in C:\projects\Tumblthree\src\TumblThree\TumblThree.Domain\Models\Files\Files.cs:line 110
   at TumblThree.Applications.Controllers.ManagerController.GetIFilesCore(String directory) in C:\projects\Tumblthree\src\TumblThree\TumblThree.Applications\Controllers\ManagerController.cs:line 351
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TumblThree.Applications.Controllers.ManagerController.<LoadAllDatabasesAsync>d__62.MoveNext() in C:\projects\Tumblthree\src\TumblThree\TumblThree.Applications\Controllers\ManagerController.cs:line 300
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TumblThree.Applications.Controllers.ManagerController.<LoadDataBasesAsync>d__58.MoveNext() in C:\projects\Tumblthree\src\TumblThree\TumblThree.Applications\Controllers\ManagerController.cs:line 205
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TumblThree.Applications.Controllers.ManagerController.<InitializeAsync>d__52.MoveNext() in C:\projects\Tumblthree\src\TumblThree\TumblThree.Applications\Controllers\ManagerController.cs:line 175
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at TumblThree.Domain.Models.Files.Files.LoadCore(String fileLocation) in C:\projects\Tumblthree\src\TumblThree\TumblThree.Domain\Models\Files\Files.cs:line 159
   at TumblThree.Domain.Models.Files.Files.Load(String fileLocation) in C:\projects\Tumblthree\src\TumblThree\TumblThree.Domain\Models\Files\Files.cs:line 110
   at TumblThree.Applications.Controllers.ManagerController.GetIFilesCore(String directory) in C:\projects\Tumblthree\src\TumblThree\TumblThree.Applications\Controllers\ManagerController.cs:line 351
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TumblThree.Applications.Controllers.ManagerController.<LoadAllDatabasesAsync>d__62.MoveNext() in C:\projects\Tumblthree\src\TumblThree\TumblThree.Applications\Controllers\ManagerController.cs:line 300
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TumblThree.Applications.Controllers.ManagerController.<LoadDataBasesAsync>d__58.MoveNext() in C:\projects\Tumblthree\src\TumblThree\TumblThree.Applications\Controllers\ManagerController.cs:line 205
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TumblThree.Applications.Controllers.ManagerController.<InitializeAsync>d__52.MoveNext() in C:\projects\Tumblthree\src\TumblThree\TumblThree.Applications\Controllers\ManagerController.cs:line 175<---

**Comment by thomas694** [comment]
You can have a look on the [preview version](https://ci.appveyor.com/api/buildjobs/rgj20lgvl3nm1all/artifacts/artifacts%2FTumblThree-v1.6.3-x64-Application.zip), whether it fixes your problem.

**Comment by MSWallack** [comment]
The queue works again in the preview version. What changed (in terms someone who hasn't written a line of code in 30 years would understand...)?

**Comment by thomas694** [comment]
Actually the loading of one of your blog databases produced an error that wasn't handled. The error was bubbling up too far and prevented the further and proper initialization of other things including the queue.

**Comment by thomas694** [comment]
The issue has been fixed and closed.
