### ISSUE TITLE
Tumblr Search does not seem to be working

### ISSUE THREAD

**Issue by thomas694** [TumblThreeApp/TumblThree#190]
The following has been submitted:

Tumblr Search does not seem to be working.
Seeing this error in the logs:
20211123 06:55:24.081 Err TumblrSearchCrawler.CrawlPageAsync: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: 'System.Dynamic.ExpandoObject' does not contain a definition for 'timelines'
at CallSite.Target(Closure , CallSite , Object )
at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
at CallSite.Target(Closure , CallSite , Object )
at TumblThree.Applications.Crawler.TumblrSearchCrawler.d__10.MoveNext() in C:\projects\Tumblthree\src\TumblThree\TumblThree.Applications\Crawler\TumblrSearchCrawler.cs:line 119

**Comment by thomas694** [comment]
It doesn't affect safe keywords.
For the other keywords you need to be signed in to be able to search them and download the posts.
