### ISSUE TITLE
Error 1: Could not load file library. Invalid byte encoding

### ISSUE THREAD

**Issue by complaintspleasetakeanumber** [TumblThreeApp/TumblThree#193]
![image](https://user-images.githubusercontent.com/95627723/145065595-ebb25d9e-dca9-40bf-95d7-91c7ea8f47c6.png)

I updated to 2.4.4.233 and now I get this - Error 1: Could not load file library. Invalid byte encoding

**Comment by thomas694** [comment]
> One of the files has changed for whatever reason. Can you please have a lock at the log file (normally %LOCALAPPDATA%\TumblThree\TumblThree.log), if you see any errors or hints at the time you get the error message?

> It could be that you opened one of the files in the Index folder in another program / text editor even if you did not (knowingly) save it there? At least one of the files has a UTF/Unicode format now which is not supported.
> 
> To find the file that makes the problems you can close TumblThree and move the files from the Index folder to a backup location. Then move each blog's files (e.g. abc.tumblr and abc_files.tumblr) back to the Index folder and start TumblThree afterwards. Close it again and repeat the step until TumblThree no longer loads the files, the last one added is the broken one. If you have many blogs, you can use small groups (e.g. 5 or 10 at once) to first narrow it down.

[#160]

**Comment by complaintspleasetakeanumber** [comment]
Thanks, time consuming process but that helps!

**Comment by thomas694** [comment]
Can you copy me the block where it says "Invalid byte encoding" from the TumblThree log file?

**Comment by thomas694** [comment]
The issue has been closed. You can still comment. Feel free to ask for reopening the issue if needed.

**Comment by complaintspleasetakeanumber** [comment]
What is the log file telling me?

20221230 07:38:43.825	Inf 	TumblThree start
20221230 07:38:43.826	Inf 	AppPath: C:\Users\cratt\Downloads\TumblThree-v2.7.1-x64-Application
20221230 07:38:43.827	Inf 	AppSettingsPath: C:\Users\cratt\AppData\Local\TumblThree\Settings
20221230 07:38:43.827	Inf 	LogFilename: C:\Users\cratt\AppData\Local\TumblThree\TumblThree.log
20221230 07:38:43.827	Inf 	Version: 2.9.3.376
20221230 07:38:43.827	Inf 	IsLongPathSupported: False
20221230 07:38:44.297	Err 	ManagerController.LoadDataBasesAsync: System.Xml.XmlException: Invalid byte encoding.
   at System.Runtime.Serialization.Json.JsonEncodingStreamWrapper.ReadEncoding(Byte b1, Byte b2)
   at System.Runtime.Serialization.Json.JsonEncodingStreamWrapper.ReadEncoding()
   at System.Runtime.Serialization.Json.JsonEncodingStreamWrapper.InitForReading(Stream inputStream, Encoding expectedEncoding)
   at System.Runtime.Serialization.Json.XmlJsonReader.SetInput(Stream stream, Encoding encoding, XmlDictionaryReaderQuotas quotas, OnXmlDictionaryReaderClose onClose)
   at System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(Stream stream)
   at TumblThree.Domain.Models.Blogs.Blog.LoadCore(String fileLocation) in C:\projects\Tumblthree\src\TumblThree\TumblThree.Domain\Models\Blogs\Blog.cs:line 1063
   at TumblThree.Domain.Models.Blogs.Blog.Load(String fileLocation) in C:\projects\Tumblthree\src\TumblThree\TumblThree.Domain\Models\Blogs\Blog.cs:line 1052
   at TumblThree.Applications.Controllers.ManagerController.GetIBlogsCore(String directory) in C:\projects\Tumblthree\src\TumblThree\TumblThree.Applications\Controllers\ManagerController.cs:line 294
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at TumblThree.Applications.Controllers.ManagerController.<LoadLibraryAsync>d__63.MoveNext() in C:\projects\Tumblthree\src\TumblThree\TumblThree.Applications\Controllers\ManagerController.cs:line 245
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TumblThree.Applications.Controllers.ManagerController.<LoadDataBasesAsync>d__62.MoveNext() in C:\projects\Tumblthree\src\TumblThree\TumblThree.Applications\Controllers\ManagerController.cs:line 216
