### ISSUE TITLE
Problem with existing database after program loading

### ISSUE THREAD

**Issue by saturnengr** [TumblThreeApp/TumblThree#227]
**Describe the bug**
In version 2.5.5.286 -> Cannot get any tumblr archive in the queue to download.   Believe the problem occurs on program load Program lists error on initial load: Error 1: Could not load file in library: Invalid byte encoding.

**To Reproduce**
1. just load the program

**Screenshots**
How about a log file instead?  Verbose log file turned on.  You can see this is happening upon program load:  

Exception message

Invalid byte encoding.

Exception type

System.Xml.XmlException

Callstack

   at System.Runtime.Serialization.Json.JsonEncodingStreamWrapper.ReadEncoding(Byte b1, Byte b2)
   at System.Runtime.Serialization.Json.JsonEncodingStreamWrapper.ReadEncoding()
   at System.Runtime.Serialization.Json.JsonEncodingStreamWrapper.InitForReading(Stream inputStream, Encoding expectedEncoding)
   at System.Runtime.Serialization.Json.JsonEncodingStreamWrapper..ctor(Stream stream, Encoding encoding, Boolean isReader)
   at System.Runtime.Serialization.Json.XmlJsonReader.SetInput(Stream stream, Encoding encoding, XmlDictionaryReaderQuotas quotas, OnXmlDictionaryReaderClose onClose)
   at System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(Stream stream)
   at TumblThree.Domain.Models.Files.Files.LoadCore(String fileLocation) in C:\projects\Tumblthree\src\TumblThree\TumblThree.Domain\Models\Files\Files.cs:line 124
   at TumblThree.Domain.Models.Files.Files.Load(String fileLocation) in C:\projects\Tumblthree\src\TumblThree\TumblThree.Domain\Models\Files\Files.cs:line 110
   at TumblThree.Applications.Controllers.ManagerController.GetIFilesCore(String directory) in C:\projects\Tumblthree\src\TumblThree\TumblThree.Applications\Controllers\ManagerController.cs:line 401
   at TumblThree.Applications.Controllers.ManagerController.<>c__DisplayClass68_0.<GetIFilesAsync>b__0() in C:\projects\Tumblthree\src\TumblThree\TumblThree.Applications\Controllers\ManagerController.cs:line 383
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TumblThree.Applications.Controllers.ManagerController.<LoadAllDatabasesAsync>d__66.MoveNext() in C:\projects\Tumblthree\src\TumblThree\TumblThree.Applications\Controllers\ManagerController.cs:line 340
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Waf.Applications.AsyncDelegateCommand.<Execute>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

Inner exception

-

TumblThree version

TumblThree 2.5.5.286 (32-bit)

Windows version

Windows 10 Pro 64-bit, version 2009 (10.0.19042.1586)

.Net Framework version

4.0.30319.42000 32 Bit

Default browser

Google Chrome (99.0.4844.51)

Region settings

chr-Cher-US, US
 
**Additional context**
99% certain I have a file that's become corrupted.   But don't see how to figure out what file it is.   

Things that work:  
* Checking online blog status
* Opening blog in both tumblr and tumbex
* Showing details
* moving blogs to the queue
* Clicking on crawl -- but nothing happens.  But the buttons shift focus and enable/disable status (greyed out or not).
* Settings 
* About
* Adding blogs
* Removing blogs

What doesn't work:  
* downloading any blog, whether a new blog or an existing blog
* Clocking on pause or stop after clicking on crawl

Any assistance would be appreciated.

**Comment by thomas694** [comment]
> One of the files has changed for whatever reason. The log file is located at `%LOCALAPPDATA%\TumblThree\TumblThree.log`

> It could be that you opened one of the files in the Index folder in another program / text editor even if you did not (knowingly) save it there? At least one of the files has a UTF/Unicode format now which is not supported.
> 
> To find the file that makes the problems you can close TumblThree and move the files from the Index folder to a backup location. Then move each blog's files (e.g. abc.tumblr and abc_files.tumblr) back to the Index folder and start TumblThree afterwards. Close it again and repeat the step until TumblThree no longer loads the files, the last one added is the broken one. If you have many blogs, you can use small groups (e.g. 5 or 10 at once) to first narrow it down.

[#160]

If you found the changed file, you can use a text editor which is capable of and change it back to UTF-8 encoding. Then it should be usable again in TumblThree.

**Comment by saturnengr** [comment]
Found it.  I deleted the offending file and re-added it.   All working now.   

It was literally the last place I looked.   Of course, it should always be the last place you look.  Primarily because if you find the problem and are still looking, that's a good definition of crazy.  

Thank you

**Comment by thomas694** [comment]
The issue has been closed. You can still comment. Feel free to ask for reopening the issue if needed.
