### ISSUE TITLE
Unexpected error occured. The application state might be corrupted

### ISSUE THREAD

**Issue by T-prog3** [TumblThreeApp/TumblThree#251]
1. Got the following error every time when i tried to switch the active collection.
2. It happened after about a hours of use.
3. Restart made it go away.

```
Exception message

Exception 2

Exception type

System.Exception

Callstack

   at TumblThree.Applications.Services.ManagerService.CrawlerService_ActiveCollectionIdChanged(Object sender, EventArgs e) in C:\projects\Tumblthree\src\TumblThree\TumblThree.Applications\Services\ManagerService.cs:line 51
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Windows.Data.CollectionView.OnCurrentChanged()
   at System.Windows.Data.ListCollectionView.MoveCurrentToPosition(Int32 position)
   at System.Windows.Controls.Primitives.Selector.SetCurrentToSelected()
   at System.Windows.Controls.Primitives.Selector.SelectionChanger.End()
   at System.Windows.Controls.Primitives.Selector.SelectionChanger.SelectJustThisItem(ItemInfo info, Boolean assumeInItemsCollection)
   at System.Windows.Controls.ComboBox.NotifyComboBoxItemMouseUp(ComboBoxItem comboBoxItem)
   at System.Windows.Controls.ComboBoxItem.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

Inner exception

System.InvalidOperationException: 'Refresh' is not allowed during an AddNew or EditItem transaction.
   at System.Windows.Data.CollectionView.Refresh()
   at TumblThree.Applications.Services.ManagerService.CrawlerService_ActiveCollectionIdChanged(Object sender, EventArgs e) in C:\projects\Tumblthree\src\TumblThree\TumblThree.Applications\Services\ManagerService.cs:line 47

TumblThree version

TumblThree 2.6.3.316 (64-bit)
```

**Comment by thomas694** [comment]
I know that error, but couldn't reproduce it on purpose. Have to find the root cause yet.

**Comment by T-prog3** [comment]
Last time when i got the error i had just added three new blogs and made a short Personal Note after each input.
I then changed the collection and it popped up.
After restart all the blogs was still there, but the Personal Notes were all gone.
