### ISSUE TITLE
Not downloading liked by

### ISSUE THREAD

**Issue by jjdnl** [TumblThreeApp/TumblThree#346]
**Describe the bug**
Liked-by type of blog is not downloading since version 2.8.0.347. Reverting to previous version solves the problem

**To Reproduce**
1. Click on blog
2. click on download
3. errors messages in blue bar on top of screen

**Expected behavior**
download without errors

**Desktop (please complete the following information):**
 - TumblThree version: 2.8.0.347
 - OS: [e.g. Windows 10 Home] Windows 10 pro build 19044.1889
 - Browser [e.g. Chrome, Safari, IE, Edge] Firefox 
 - Version [e.g. 22] 104.0.2 (64-bit)

**Additional context**
ThumblThreeLog message:
20220915 01:00:00.523	Vrb 	TumblrLikedByCrawler.Crawl:Start
20220915 01:00:00.878	Vrb 	TumblrLikedByCrawler.Crawl:Start
20220915 01:00:01.340	Err 	TumblrLikedByCrawler:CrawlPageAsync: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot perform runtime binding on a null reference
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at TumblThree.Applications.Crawler.TumblrLikedByCrawler.ExtractPosts(String document) in C:\projects\Tumblthree\src\TumblThree\TumblThree.Applications\Crawler\TumblrLikedByCrawler.cs:line 366
   at TumblThree.Applications.Crawler.TumblrLikedByCrawler.<CrawlPageAsync>d__16.MoveNext() in C:\projects\Tumblthree\src\TumblThree\TumblThree.Applications\Crawler\TumblrLikedByCrawler.cs:line 190

Debug Log:
[0915/062106.933:WARNING:browser_info.cc(298)] Returning a speculative frame for 47244640261 [11,5]
[0915/062107.269:ERROR:ssl_client_socket_impl.cc(996)] handshake failed; returned -1, SSL error code 1, net_error -200
[0915/062107.270:WARNING:browser_info.cc(298)] Returning a speculative frame for 47244640261 [11,5]

**Comment by thomas694** [comment]
Thanks for reporting a bug. It will be fixed shortly.

**Comment by thomas694** [comment]
The issue has been fixed and closed. You can still comment. Feel free to ask for reopening the issue if needed.
