### ISSUE TITLE
Crash during Tumblr privacy consent

### ISSUE THREAD

**Issue by Pleochism** [TumblThreeApp/TumblThree#356]
**Describe the bug**
When clicking "Privacy consent" for Tumblr, after the popup closes, the app throws an error.

**To Reproduce**
1. Go to Settings
2. Click on Privacy consent for Tumblr
3. Complete it and close the popup

**Expected behavior**
The popup should close and the "Privacy consent" box should be greyed out.

**Desktop (please complete the following information):**
 - TumblThree version: 2.8.2
 - OS: Win 10 Professional
 - Browser Chrome
 - Version: latest

**Additional context**

Exception message
Invalid URI: The hostname could not be parsed.

Exception type
System.UriFormatException

Callstack
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at TumblThree.Presentation.Views.AuthenticateView.<GetCookies>d__11.MoveNext() in C:\projects\Tumblthree\src\TumblThree\TumblThree.Presentation\Views\AuthenticateView.xaml.cs:line 81
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TumblThree.Applications.ViewModels.SettingsViewModel.<PrivacyConsent>d__492.MoveNext() in C:\projects\Tumblthree\src\TumblThree\TumblThree.Applications\ViewModels\SettingsViewModel.cs:line 1091
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Waf.Applications.AsyncDelegateCommand.<Execute>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

Inner exception

-

TumblThree version
TumblThree 2.8.2.352 (64-bit)

Windows version
Windows 10 Pro 64-bit, version 21H2 (10.0.19044.2006)

.Net Framework version
4.0.30319.42000 64 Bit

.Net Version Support

Default browser
Firefox (105.0.1)

Region settings
af-ZA, ZA

**Comment by thomas694** [comment]
Thanks for reporting a bug.
It has been fixed in 50f92742eba7801f6cbead0a1731d7e20ec067b5 and comes in the next version.

**Comment by thomas694** [comment]
The issue has been fixed and closed. You can still comment. Feel free to ask for reopening the issue if needed.
