### ISSUE TITLE
Error 1: Likes: Error parsing post

### ISSUE THREAD

**Issue by nateify** [TumblThreeApp/TumblThree#374]
**Describe the bug**
Error 1 parsing when downloading likes

**To Reproduce**
I am downloading my likes directly by the URL `tumblr.com/likes` while logged in, accepted privacy statement, using Tumblr SVC API. It gets most of the way through but fails at a certain point.

**Screenshots**
Some screenshots of the setup:
https://files.catbox.moe/krzeos.png
https://files.catbox.moe/g8pbwx.png 

Log file right after the error occurred: https://pastebin.com/raw/jYUbmqGG

**Desktop (please complete the following information):**
 - TumblThree version: 2.8.3.357
 - OS: Windows 10

**Comment by thomas694** [comment]
Thanks for reporting a bug. We'll take a look at it.

**Comment by thomas694** [comment]
The issue has been fixed and closed. You can still comment. Feel free to ask for reopening the issue if needed.

**Comment by nateify** [comment]
Hi, thanks for the update. I am running into the same Error 1 parsing though it stopped on a different post and with a new log:
https://pastebin.com/raw/RizkyUvM

**Comment by thomas694** [comment]
That wasn't intentional.
Your screenshots and log excerpts always help to get directly to the problem location. 👍🏻  Better than a statement "all my blogs fail", even if you doubt it, because there are successful tests with some sample blogs before a new version is released. 

Could it be that now a different kind of text posts like quotes, question and answers fails? Are they just reblogs or was new content added?
If you don't mind, you could provide (through our feedback dialog or my profile email) links to failing posts, it would help even more.

**Comment by nateify** [comment]
> That wasn't intentional. Your screenshots and log excerpts always help to get directly to the problem location. 👍🏻 Better than a statement "all my blogs fail", even if you doubt it, because there are successful tests with some sample blogs before a new version is released.
> 
> Could it be that now a different kind of text posts like quotes, question and answers fails? Are they just reblogs or was new content added? If you don't mind, you could provide (through our feedback dialog or my profile email) links to failing posts, it would help even more.

Where can I find the post it fails on?

**Comment by thomas694** [comment]
It's not directly logging which posts or urls fail. But maybe if the errors already start directly after pressing "download", you can see which are missing by comparing it to the version you see in your browser. Or you could add the url as a new blog, or use a new "download location" for testing.

**Comment by nyckidryan** [comment]
Same issue downloading via `http://www.tumblr.com/liked/by/[blog]`

Downloaded items: 46
Newly downloaded items: 46
Number of downloadable items: 48
(actual blog likes: over 59,000)

Downloading images only, all other download options turned off, stock config/fresh installation:

![tumblthree-config](https://user-images.githubusercontent.com/77482749/199921435-3b9ca65d-1b8f-42cf-b74c-743cd9e75d2f.png)

Error 1: [blog]: Error parsing post!

From TumblThree.log:

20221104 03:36:19.216	Inf 	TumblThree start
20221104 03:36:19.217	Inf 	AppPath: J:\TumblThree-v2.9.0
20221104 03:36:19.217	Inf 	AppSettingsPath: D:\Users\ryan\AppData\Local\TumblThree\Settings
20221104 03:36:19.217	Inf 	LogFilename: J:\TumblThree-v2.9.0\TumblThree.log
20221104 03:36:19.217	Inf 	Version: 2.9.0.363
20221104 03:36:19.218	Inf 	IsLongPathSupported: True

20221104 03:36:45.576	Err 	TumblrLikedByCrawler:CrawlPageAsync: System.Exception: 429 - Limit exceeded.
   at TumblThree.Applications.Crawler.AbstractTumblrCrawler.RetrieveOriginalImageUrl(String url, Int32 width, Int32 height, Boolean isInline) in C:\projects\Tumblthree\src\TumblThree\TumblThree.Applications\Crawler\AbstractTumblrCrawler.cs:line 446
   at TumblThree.Applications.Crawler.AbstractTumblrCrawler.AddTumblrPhotoUrl(String text, Post post) in C:\projects\Tumblthree\src\TumblThree\TumblThree.Applications\Crawler\AbstractTumblrCrawler.cs:line 206
   at TumblThree.Applications.Crawler.TumblrLikedByCrawler.AddPhotoUrlToDownloadList(String document) in C:\projects\Tumblthree\src\TumblThree\TumblThree.Applications\Crawler\TumblrLikedByCrawler.cs:line 555
   at TumblThree.Applications.Crawler.TumblrLikedByCrawler.<AddUrlsToDownloadListAsync>d__26.MoveNext() in C:\projects\Tumblthree\src\TumblThree\TumblThree.Applications\Crawler\TumblrLikedByCrawler.cs:line 524
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at TumblThree.Applications.Crawler.TumblrLikedByCrawler.<CrawlPageAsync>d__16.MoveNext() in C:\projects\Tumblthree\src\TumblThree\TumblThree.Applications\Crawler\TumblrLikedByCrawler.cs:line 208

20221104 03:36:48.662	Err 	TumblrLikedByCrawler:CrawlPageAsync: System.Exception: 429 - Limit exceeded.
   at TumblThree.Applications.Crawler.AbstractTumblrCrawler.RetrieveOriginalImageUrl(String url, Int32 width, Int32 height, Boolean isInline) in C:\projects\Tumblthree\src\TumblThree\TumblThree.Applications\Crawler\AbstractTumblrCrawler.cs:line 446
   at TumblThree.Applications.Crawler.AbstractTumblrCrawler.AddTumblrPhotoUrl(String text, Post post) in C:\projects\Tumblthree\src\TumblThree\TumblThree.Applications\Crawler\AbstractTumblrCrawler.cs:line 206
   at TumblThree.Applications.Crawler.TumblrLikedByCrawler.AddPhotoUrlToDownloadList(String document) in C:\projects\Tumblthree\src\TumblThree\TumblThree.Applications\Crawler\TumblrLikedByCrawler.cs:line 555
   at TumblThree.Applications.Crawler.TumblrLikedByCrawler.<AddUrlsToDownloadListAsync>d__26.MoveNext() in C:\projects\Tumblthree\src\TumblThree\TumblThree.Applications\Crawler\TumblrLikedByCrawler.cs:line 524
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at TumblThree.Applications.Crawler.TumblrLikedByCrawler.<CrawlPageAsync>d__16.MoveNext() in C:\projects\Tumblthree\src\TumblThree\TumblThree.Applications\Crawler\TumblrLikedByCrawler.cs:line 208

20221104 03:36:50.586	Err 	TumblrLikedByCrawler:CrawlPageAsync: System.Exception: 429 - Limit exceeded.
   at TumblThree.Applications.Crawler.AbstractTumblrCrawler.RetrieveOriginalImageUrl(String url, Int32 width, Int32 height, Boolean isInline) in C:\projects\Tumblthree\src\TumblThree\TumblThree.Applications\Crawler\AbstractTumblrCrawler.cs:line 446
   at TumblThree.Applications.Crawler.AbstractTumblrCrawler.AddTumblrPhotoUrl(String text, Post post) in C:\projects\Tumblthree\src\TumblThree\TumblThree.Applications\Crawler\AbstractTumblrCrawler.cs:line 206
   at TumblThree.Applications.Crawler.TumblrLikedByCrawler.AddPhotoUrlToDownloadList(String document) in C:\projects\Tumblthree\src\TumblThree\TumblThree.Applications\Crawler\TumblrLikedByCrawler.cs:line 555
   at TumblThree.Applications.Crawler.TumblrLikedByCrawler.<AddUrlsToDownloadListAsync>d__26.MoveNext() in C:\projects\Tumblthree\src\TumblThree\TumblThree.Applications\Crawler\TumblrLikedByCrawler.cs:line 524
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at TumblThree.Applications.Crawler.TumblrLikedByCrawler.<CrawlPageAsync>d__16.MoveNext() in C:\projects\Tumblthree\src\TumblThree\TumblThree.Applications\Crawler\TumblrLikedByCrawler.cs:line 208

**Comment by thomas694** [comment]
> Same issue downloading ...

Not same issue, maybe similar error message shown, but actually different reason.
Here it's a "429 limit exceeded" error. Tumblr says you downloaded too much in the measured time frame. You probably did and maybe are using more than one instance (web browser, app) to access their site at once.

We'll change how this error message is displayed.

**Comment by IThatAngel** [comment]
103 days since the last comment on this, I'm having the same issue here, and it's not just affecting my likes link. I tested it on another blog and the issue was there too.  Most of the errors I got from them were from parsing posts (1).
After it downloads a couple tens or hundreds of posts (I noticed the size depends on the size of posts of a clog), it stops after a certain point. 
Right-clicking a selected process via "enqueue selection" only scans the number of downloadable items and increases it, without downloading anything.  _(This mainly happens in my liked selection)._
The download process is practically stuck. No changes in the downloaded items tab, nothing, nadah. 

Likes
![TumblThree_oX0XNu9vQd](https://user-images.githubusercontent.com/66276581/224025347-239fce2c-d74f-429d-9fa1-7cb3e6714199.png)
![TumblThree_JUXETQeEZR](https://user-images.githubusercontent.com/66276581/224025789-e36aa101-b669-49b1-bf3a-92232aa4a338.png)
`https://www.tumblr.com/likes`
(The number of liked posts in Tumblr itself was 5,5k)

The solo blog in question.
![TumblThree_KvVOXGSFim](https://user-images.githubusercontent.com/66276581/224025549-f87329ac-e59c-41bc-8f8c-38f4d97f66c6.png)
![TumblThree_RqZWFhw2mg](https://user-images.githubusercontent.com/66276581/224025808-8b78dcdc-0ed0-4f6a-be6f-6d79b33eb1cb.png)
`https://floatingchromeorb.tumblr.com/archive`

Tried switching crawler detection, Still nothing.

Last thing I'd like to mention, I tried tinkering in the settings, switching some log setting to "error" fetched me this.

![TumblThree_4PGdd6Y5uD](https://user-images.githubusercontent.com/66276581/224027342-63919aae-6f05-4a99-99f2-1674f10f299a.png)

I switched it off to try something else, later I tried switching this back on and error 2 never showed up for me again.

- TumblThree version: 2.10.0.384
- OS: Windows 10 Home

I'm not a deeply technical person, since I couldn't find any log file that was mentioned earlier, I hope you understand.

**Comment by thomas694** [comment]
@IThatAngel 

You can find the log file here (%LOCALAPPDATA%\TumblThree\TumblThree.log), you can copy & paste it in windows file explorer.

Error 2 was a temporary error, something wasn't downloadable at that time. If the error is gone it's ok.

The mentioned blog is a small one. Comparing the downloaded items against the one in the browser it showed that all has been downloaded, only the number of 15 downloaded images isn't added to the numbers for some reason.
We'll have a look.

**Comment by IThatAngel** [comment]
Found the log in question. (user folder name will be replaced in here with █ █ █ for privacy concerns, sorry about that)

20230309 13:46:09.372	Inf 	TumblThree start
20230309 13:46:09.373	Inf 	AppPath: G:\Users\█ █ █\Documents\TumblThree-v2.10.0-x64-Application
20230309 13:46:09.373	Inf 	AppSettingsPath: G:\Users\█ █ █\Documents\TumblThree-v2.10.0-x64-Application\
20230309 13:46:09.373	Inf 	LogFilename: G:\Users\█ █ █\Documents\TumblThree-v2.10.0-x64-Application\TumblThree.log
20230309 13:46:09.373	Inf 	Version: 2.10.0.384
20230309 13:46:09.373	Inf 	IsLongPathSupported: True

20230309 13:48:50.541	Inf 	TumblThree start
20230309 13:48:50.542	Inf 	AppPath: G:\Users\█ █ █\Documents\TumblThree-v2.10.0-x64-Application
20230309 13:48:50.542	Inf 	AppSettingsPath: G:\Users\█ █ █\Documents\TumblThree-v2.10.0-x64-Application\
20230309 13:48:50.542	Inf 	LogFilename: G:\Users\█ █ █\Documents\TumblThree-v2.10.0-x64-Application\TumblThree.log
20230309 13:48:50.543	Inf 	Version: 2.10.0.384
20230309 13:48:50.543	Inf 	IsLongPathSupported: True

**Comment by thomas694** [comment]
Sure, you can mask personal details.
But as you may have seen both blocks contain the same information except the timestamps. It's the current version running in portable mode.
A part with an error message would help.

**Comment by thomas694** [comment]
@IThatAngel 
Please try the newest version.

**Comment by IThatAngel** [comment]
> 

Sorry for the late response, I only got notified by this via email. I downloaded the latest version as you asked.
So far I had no issue downloading smaller blogs, however when I attempted to download liked posts again, it failed to detect an account... which I had already authenticated.
I tried uninstalling and reinstalling it +authenticating again. And I still get the same error with the liked posts.  

That's all I think of to mention at this moment.

**Comment by thomas694** [comment]
Please try the new [test version](https://ci.appveyor.com/api/buildjobs/i0ekcael1mi1im2a/artifacts/artifacts%2FTumblThree-v2.10.1-x64-Application.zip) and check if the authentication works better for you.
You can conveniently extract the zip file into a new folder, no need to remove your normal installation folder for testing.

**Comment by IThatAngel** [comment]
> Please try the new [test version](https://ci.appveyor.com/api/buildjobs/i0ekcael1mi1im2a/artifacts/artifacts%2FTumblThree-v2.10.1-x64-Application.zip) and check if the authentication works better for you. You can conveniently extract the zip file into a new folder, no need to remove your normal installation folder for testing.

I downloaded the version you provided. Sadly, the authentication issue still persists. I even logged in before trying to download likes again.
![TumblThree_4wVijmNUAL](https://user-images.githubusercontent.com/66276581/230345313-337a20e7-5ee4-4cbd-bc7c-d274c71de0f1.png)
![TumblThree_MwIdqEwKr6](https://user-images.githubusercontent.com/66276581/230345328-6dd6678a-23ac-4f86-99d5-8263d5ad48ba.png)
On the bright side, at least I can download other blogs with no issues now,

**Comment by azizomar9** [comment]
@thomas694 I am having the same issue as @IThatAngel was having as well. I can't download my likes anymore because it says I am not logged in when I am. Is there a solution to the issue yet?

**Comment by thomas694** [comment]
Please try the newest [test version](https://ci.appveyor.com/api/buildjobs/3nvee9auinxi1tpm/artifacts/artifacts%2FTumblThree-v2.10.2-x64-Application.zip) and let us know the results.

**Comment by IThatAngel** [comment]
> Please try the newest [test version](https://ci.appveyor.com/api/buildjobs/3nvee9auinxi1tpm/artifacts/artifacts%2FTumblThree-v2.10.2-x64-Application.zip) and let us know the results.

Aaaand nothing has changed...
Still can't download my likes, but can for other blogs.
Even deleted previous folders before running this one and authenticating.
Still nadah. Oh well.

**Comment by joaobarros** [comment]
I had the same not logged in error and could only get it to work when I changed to https://www.tumblr.com/liked/by/[blog name] format but I see it was already tried that way.
The normal like format should work or the /liked/by/ documented as it can get quite frustrating to get it going.

**Comment by thomas694** [comment]
@ all
Please try the newest [test version](https://ci.appveyor.com/api/buildjobs/r79w0i6vrb3ut55p/artifacts/artifacts%2FTumblThree-v2.10.3-x64-Application.zip) and let us know the results. Before doing the test download of your Likes, delete/rename the old log file, set the `Log Level` to `Verbose` and ensure you are logged in.

Does it fail to download posts from the beginning or after a while?
Please keep the last 1-3 pages from the log file and send the zipped file and any useful info by email, or upload it to e.g. Pastebin and send this link by email or feedback dialog.
