### ISSUE TITLE
я больше не могу аутентифицировать tumblr.

### ISSUE THREAD

**Issue by olegsh23** [TumblThreeApp/TumblThree#480]
**Describe the bug**

**To Reproduce**
2. Click on '...'
3. Scroll down to '...'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - TumblThree version: [e.g. 1.0.11.3]
 - OS: [e.g. Windows 10 Home]
 - Browser [e.g. Chrome, Safari, IE, Edge]

**Additional context**

**Comment by olegsh23** [comment]
перестала видить пароль и логин, удолял Cookies.json, не помогает, иногда на короткое время и выбрасывает
пользуюсь довно началось вчера

**Comment by olegsh23** [comment]
через 3 минуты разрывает соединение и аутентифицировать не хачет

**Comment by thomas694** [comment]
Please write in english. You can also use an online translator.

**Comment by vozmor** [comment]
Same problem here.

After starting the app, I always routinely check the authentication. The problem started on Friday, not at start but after a couple of hours of normal functioning. The app does not authenticate Tumblr at all:
1) I click on Authenticate button
2) The window ("Authenticate view") pops up properly, I can see in it that I am logged in Tumblr properly
3) I close the window
4) The settings doesn't change and still says I am logged out, the Authenticate button remains active.

I tried deleting the Cookies.json, it didn't help. 

Twitter authentication works properly.

Another anomaly that started on Friday, too: the app indicates that about 20% of the Tumblr pages I am following with the app are offline. It is independent from the type: standard page, hidden page, even search and tag search, quite strange.

Both errors have disappeared twice so far, simultaneously, without my doing anything, but only for a couple of minutes.

**Comment by honeylemontea** [comment]
I'm having the problem, too even in the latest update. It will log me in but it won't authenticate me.

**Comment by MiriamSexton** [comment]
Having the same issue

**Comment by Ssurgul** [comment]
I just grabbed the code today for the first time, and also having the issue.

I can log in through the browser after clicking the Authenticate button. I am able to see, scroll, and even repost/start new content through that browser. But it's not keeping the cookies for either the base login nor the Privacy Consent window. (I logged in through the same process to Twitter, and that captured the cookies properly.)

**Comment by vozmor** [comment]
The authentication error has not disappeared with the new release (2.12.0.438).

There is another strange behaviour (it had already existed before the latest version has been released): all the **Tumblr Search** and **Tumblr Tag Search** entries are appearingly offline. 

If I bulk select them all and check their online status, one in twenty or so switches to online and I can download them. However, if I check their online status one by one, eight in ten switch online. Nevertheless, almost all of them switch back to offline within 5-10 minutes. 

As these are searches, not blogs, I wonder what the problem can be.

**Comment by thomas694** [comment]
The Search and Tag Search also need authentication, so the problems are related.
As soon as the authentication works again, the online check and download of Searches work again.

Did someone else experience that the authentication problems are less frequent when setting "concurrent blogs" to 1?
Or is it just good luck of some users?

**Comment by vozmor** [comment]
@thomas694 

For me the concurrent blogs has always been 1. 

The problem persists <very sad> When I restart the program and authenticate Tumblr it works for 5-15 minutes, but only when manually checking the blog's online status first, one by one. When bulk checking, about 10% is indicated being online, randomly, and even those switch back to offline soon.

**Comment by Orudeon** [comment]
This problem is still happening. It's a complete tossup as to whether TumblThree will authenticate, and even then it seems like it's only until I close the settings pane.

Until the problem is fixed, it seems like it doesn't work for hidden blogs at all.

**Comment by GregoryWest501** [comment]
It is still disconnecting when I am downloading a large number of blogs.   Odd thing is, if, while the download is happening, I go into setting an re-authenticate TumblThree carries on as if nothing went wrong.   Is there a way that is Tumblr disconnects TumblrThree automatically tries to reconnect a couple times before giving up?

**Comment by vozmor** [comment]
2.14.0.450 - It still doesn't authenticate  for longer than a couple of minutes, often at all :(
@FlintTD's workaround doesn't work for me, either :/

**Comment by Someonemustnothavethis** [comment]
I believe this to be Tumblr screwing around at their end.  Sometimes it works for me, sometimes not.  I usually do a big update of my 200+ blogs I follow and frequently have to log-in every 20 minutes or so.  Sometimes after the existing updates are done, I'll add some new blogs and these will run for a few hours downloading, without having to re-log-in.  Next month everything works perfectly, subsequent month it's back to logging-in every half hour(?) or so.
No matter what, this program is still a zillion times better than having to manually download or follow a lot of blogs.

**Comment by Orudeon** [comment]
Version 2.14.2.457 still can't authenticate. In twenty minutes of pushing authenticate, fiddling with stuff in the tumblr window, closing it, pushing save, and trying again, it authenticated once and only until I pushed save. Attempting to download after saving didn't work. Even on the off chance it says I'm logged in when I check settings, it doesn't matter as it still throws errors.

**Comment by Orudeon** [comment]
It's still happening as of July 8th, a year later. Even if I get it to authenticate, it breaks as soon as I push download.

Here is some log file of what's going on.

```
20250708 11:51:24.055	Inf 	TumblThree start
20250708 11:51:24.055	Inf 	AppPath: E:\Program Files\TumblThree
20250708 11:51:24.055	Inf 	AppSettingsPath: C:\Users\Matt\AppData\Local\TumblThree\Settings
20250708 11:51:24.055	Inf 	LogFilename: C:\Users\Matt\AppData\Local\TumblThree\TumblThree.log
20250708 11:51:24.056	Inf 	Version: 2.18.1.488
20250708 11:51:24.056	Inf 	IsLongPathSupported: True
20250708 11:51:32.815	Err 	LoginService.GetTumblrUsernameAsync: System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TumblThree.Applications.Extensions.TaskTimeoutExtension.<TimeoutAfter>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TumblThree.Applications.Services.WebRequestFactory.<ReadRequestToEndAsync>d__15.MoveNext() in C:\projects\Tumblthree\src\TumblThree\TumblThree.Applications\Services\WebRequestFactory.cs:line 134
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TumblThree.Applications.Services.LoginService.<GetUsernameAsync>d__20.MoveNext() in C:\projects\Tumblthree\src\TumblThree\TumblThree.Applications\Services\LoginService.cs:line 270
20250708 11:51:32.832	Err 	SettingsViewModel.UpdateLoginAsync: System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TumblThree.Applications.Extensions.TaskTimeoutExtension.<TimeoutAfter>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TumblThree.Applications.Services.WebRequestFactory.<ReadRequestToEndAsync>d__15.MoveNext() in C:\projects\Tumblthree\src\TumblThree\TumblThree.Applications\Services\WebRequestFactory.cs:line 134
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TumblThree.Applications.Services.LoginService.<GetUsernameAsync>d__20.MoveNext() in C:\projects\Tumblthree\src\TumblThree\TumblThree.Applications\Services\LoginService.cs:line 294
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TumblThree.Applications.ViewModels.SettingsViewModel.<UpdateLoginAsync>d__536.MoveNext() in C:\projects\Tumblthree\src\TumblThree\TumblThree.Applications\ViewModels\SettingsViewModel.cs:line 1225
20250708 11:51:45.298	Err 	AbstractCrawler.RequestDataAsync: System.Net.WebException: The request was aborted: The request was canceled.
   at System.Net.HttpWebRequest.BeginGetResponse(AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl(Func`3 beginMethod, Func`2 endFunction, Action`1 endAction, Object state, TaskCreationOptions creationOptions)
   at System.Net.WebRequest.<GetResponseAsync>b__78_0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TumblThree.Applications.Extensions.TaskTimeoutExtension.<TimeoutAfter>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TumblThree.Applications.Services.WebRequestFactory.<ReadRequestToEnd2Async>d__16.MoveNext() in C:\projects\Tumblthree\src\TumblThree\TumblThree.Applications\Services\WebRequestFactory.cs:line 162
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at TumblThree.Applications.Crawler.AbstractCrawler.<RequestDataAsync>d__58.MoveNext() in C:\projects\Tumblthree\src\TumblThree\TumblThree.Applications\Crawler\AbstractCrawler.cs:line 153

```
