### ISSUE TITLE
Error while handling 429

### ISSUE THREAD

**Issue by T-prog3** [TumblThreeApp/TumblThree#488]
### Got the following error:
> Err 	TwitterCrawler.CrawlPageAsync: error while handling 429: System.ArgumentOutOfRangeException: Number must be either non-negative and less than or equal to Int32.MaxValue or -1.
Parameter name: millisecondsTimeout
   at System.Threading.WaitHandle.WaitOne(Int32 millisecondsTimeout, Boolean exitContext)
   at TumblThree.Applications.Crawler.TwitterCrawler.<CrawlPageAsync>d__40.MoveNext()

**Comment by thomas694** [comment]
The issue has been fixed and closed. You can still comment. Feel free to ask for reopening the issue if needed.
