### ISSUE TITLE
Could not add the blog: The given path's format is not supported

### ISSUE THREAD

**Issue by StinkySunshine** [TumblThreeApp/TumblThree#507]
I started getting this error about an hour ago. It doesn't matter what format I use when attempting to add the blog in the bottom left, check clipboard, or even removing an existing blog then importing blog list that has the removed blog in the list. I keep getting this message: **Could not add the blog: The given path's format is not supported**

I get this error whether I try https://blogname.tumblr.com/ or https://tumblr.com/blogname/. I can download from a blog, remove the blog from the list, and try to add the blog back and still get the error.

![image](https://github.com/TumblThreeApp/TumblThree/assets/58363026/5102beb4-8c2f-4232-9744-7d322310b4cb)

![image](https://github.com/TumblThreeApp/TumblThree/assets/58363026/cac02a3e-e07a-4c35-a6df-e1bf9d3ecd4b)

20240129 09:40:07.650	Err 	ManagerController:AddBlog: System.NotSupportedException: The given path's format is not supported.
   at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at TumblThree.Domain.Models.Blogs.TumblrBlog.Create(String url, String location, String filenameTemplate, Boolean isCustomDomain) in C:\projects\Tumblthree\src\TumblThree\TumblThree.Domain\Models\Blogs\TumblrBlog.cs:line 31
   at TumblThree.Applications.Controllers.ManagerController.<CheckIfCrawlableBlog>d__108.MoveNext() in C:\projects\Tumblthree\src\TumblThree\TumblThree.Applications\Controllers\ManagerController.cs:line 955
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TumblThree.Applications.Controllers.ManagerController.<AddBlogAsync>d__101.MoveNext() in C:\projects\Tumblthree\src\TumblThree\TumblThree.Applications\Controllers\ManagerController.cs:line 868
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TumblThree.Applications.Controllers.ManagerController.<AddBlog>d__86.MoveNext() in C:\projects\Tumblthree\src\TumblThree\TumblThree.Applications\Controllers\ManagerController.cs:line 625

From what I can tell the app is otherwise functioning normally

**Comment by StinkySunshine** [comment]
I was able to figure out the issue. The path to the blogs folder was indadverntently and subtly modified to be invalid and fixing that seemed to resolve the problem. Sorry for not noticing this until after submitting a bug report. I really appreciate all the hard work put into this wonderful app.
