### ISSUE TITLE
Logged in as n/a

### ISSUE THREAD

**Issue by jjdnl** [TumblThreeApp/TumblThree#520]
Since a few day i get this text after logging in 

Downloading liked by does not work any more, no errors, but also no downloads.

Error from logfile:
20240412 15:00:06.469	Err 	LoginService.ExtractUsername: Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Path '', line 0, position 0.
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at TumblThree.Applications.Services.LoginService.ExtractUsername(Provider provider, String document) in C:\projects\Tumblthree\src\TumblThree\TumblThree.Applications\Services\LoginService.cs:line 306

**Comment by johnflint1985** [comment]
It is the same as I have reported earlier, but with sa,e n/a as a login

**Comment by NikAWing** [comment]
same problem here
beside that, I can not download, it says "Image size couldn't be retrieved for a post in ..."

**Comment by AliosOlala** [comment]
Yup, same problem too.
Also, i cannot authenticate my tumblr account.
![image](https://github.com/TumblThreeApp/TumblThree/assets/167013469/04a80289-1119-417e-a581-c29a9b3e0f6a)


Error from logfile:
20240414 23:15:10.069	Err 	AbstractTumblrCrawler:RetrieveOriginalImageUrl: Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Path '', line 0, position 0.
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at TumblThree.Applications.Crawler.AbstractTumblrCrawler.DeserializeImageResponse(String s) in C:\projects\Tumblthree\src\TumblThree\TumblThree.Applications\Crawler\AbstractTumblrCrawler.cs:line 389
   at TumblThree.Applications.Crawler.AbstractTumblrCrawler.RetrieveOriginalImageUrl(String url, Int32 width, Int32 height, Boolean isInline) in C:\projects\Tumblthree\src\TumblThree\TumblThree.Applications\Crawler\AbstractTumblrCrawler.cs:line 478

**Comment by thomas694** [comment]
fixed in new version
