### ISSUE TITLE
Can't download likes - Error2: Error parsing post

### ISSUE THREAD

**Issue by vozmor** [TumblThreeApp/TumblThree#549]
Hi there,

1) When the app starts, everything is all right, I am usually already logged in, nevertheless I always check it. Downloading Tumblr blogs is all right. (Well, almost. The persisting problem of suddenly and frequently logging out after just a couple of minutes or even seconds is now much rarer).

2) When it reaches the likes it immediately stops, it doesn't download a single file, displays the the error message, and also logs me out. I can never log in again, I have to restart the app, and it usually starts already logged in again.

It is the first time I would like to download my likes. I tried it several times, I cancelled the likes "blog" and added it again, no change. I checked the previous similar bug reports and checked my Tumblr settings, too, which seem to be all right.

Log:

20240617 19:24:35.829	Err 	TumblrLikedByCrawler:CrawlPageAsync: System.FormatException: String was not recognized as a valid DateTime.
   at System.DateTimeParse.ParseExact(String s, String format, DateTimeFormatInfo dtfi, DateTimeStyles style)
   at TumblThree.Applications.Crawler.TumblrLikedByCrawler.CheckIfWithinTimespan(Int64 pagination) in C: projects\Tumblthree\src\TumblThree\TumblThree.Applications\Crawler\TumblrLikedByCrawler.cs:line 767
   at TumblThree.Applications.Crawler.TumblrLikedByCrawler.<CrawlPageAsync>d__17.MoveNext() in C:\projects\Tumblthree\src\TumblThree\TumblThree.Applications\Crawler\TumblrLikedByCrawler.cs:line 205

**Comment by thomas694** [comment]
The value you've entered in `Download from` on the details page of the Likes downloader is wrong, it needs to be in the format YYYYMMDD.

Nevertheless, we'll add an error message that describes this better.

**Comment by thomas694** [comment]
The issue has been fixed and closed. You can still comment. Feel free to ask for reopening the issue if needed.
